-- Create all required enums for CockroachDB
CREATE TYPE IF NOT EXISTS "Role" AS ENUM ('LEARNER', 'MENTOR', 'ADMIN');
CREATE TYPE IF NOT EXISTS "Difficulty" AS ENUM ('BEGINNER', 'INTERMEDIATE', 'ADVANCED');
CREATE TYPE IF NOT EXISTS "ChallengeDifficulty" AS ENUM ('EASY', 'MEDIUM', 'HARD');
CREATE TYPE IF NOT EXISTS "MentorshipStatus" AS ENUM ('PENDING', 'ACTIVE', 'COMPLETED', 'DECLINED');
CREATE TYPE IF NOT EXISTS "ProfileVisibility" AS ENUM ('PUBLIC', 'PRIVATE');
CREATE TYPE IF NOT EXISTS "VoteType" AS ENUM ('UPVOTE', 'DOWNVOTE');
CREATE TYPE IF NOT EXISTS "EmailFrequency" AS ENUM ('INSTANT', 'DAILY', 'WEEKLY');
